const LS_KEY = 'majorSystemData_v2';

const DEFAULTS = {
   0:"Saw",   1:"Day",   2:"Noah",  3:"Mew",    4:"Ra",
   5:"Law",   6:"Jaw",   7:"Key",   8:"Ava",    9:"Bay",
  10:"Daze", 11:"Dad",  12:"DNA",  13:"Dome",  14:"Dairy",
  15:"Dale", 16:"Dash", 17:"Dog",  18:"Diva",  19:"Dab",
  20:"NASA", 21:"Net",  22:"Nun",  23:"Name",  24:"Nero",
  25:"Nail", 26:"Niche",27:"Nag",  28:"Navy",  29:"Nab",
  30:"Mace", 31:"Mat",  32:"Man",  33:"Ma'am", 34:"Mare",
  35:"Mail", 36:"Mash", 37:"Mac",  38:"Mafia", 39:"Map",
  40:"Race", 41:"Rat",  42:"Rain", 43:"Ram",   44:"Ra-ra",
  45:"Rail", 46:"Rage", 47:"Rack", 48:"Rafia", 49:"Rap",
  50:"Lace", 51:"Lad",  52:"Lane", 53:"Lama",  54:"Lair",
  55:"Lily", 56:"Lash", 57:"Lake", 58:"Lava",  59:"Lab",
  60:"Chase",61:"Chat", 62:"Chain",63:"Chime", 64:"Chair",
  65:"Cello",66:"Cha-cha",67:"Check",68:"Chaff",69:"Chap",
  70:"Case", 71:"Cat",  72:"Can",  73:"Cameo", 74:"Car",
  75:"Call", 76:"Cage", 77:"Cake", 78:"Cafe",  79:"Cab",
  80:"Face", 81:"Fad",  82:"Fan",  83:"Fame",  84:"Fair",
  85:"Fall", 86:"Fish", 87:"Fog",  88:"Fife",  89:"Fab",
  90:"Base", 91:"Bat",  92:"Ban",  93:"Bam",   94:"Bar",
  95:"Ball", 96:"Bash", 97:"Back", 98:"Beef",  99:"Babe"
};

const SEM3_DATA = {
  "0100":"Vision - Dinosaur",  "0200":"Vision - Nobility",   "0300":"Vision - Moonlight",
  "0400":"Vision - Ravine",    "0500":"Vision - Lightning",   "0600":"Vision - Church",
  "0700":"Vision - Concorde",  "0800":"Vision - Fire",        "0900":"Vision - Painting",
  "1000":"Sound - Sing",       "1100":"Sound - Drum",         "1200":"Sound - Neigh",
  "1300":"Sound - Moan",       "1400":"Sound - Roar",         "1500":"Sound - Lap",
  "1600":"Sound - Shh",        "1700":"Sound - Gong",         "1800":"Sound - Violine",
  "1900":"Sound - Piano",      "2000":"Smell - Seaweed",      "2100":"Smell - Tar",
  "2200":"Smell - Nutmeg",     "2300":"Smell - Mint",         "2400":"Smell - Rose",
  "2500":"Smell - Leather",    "2600":"Smell - Cheese",       "2700":"Smell - Coffee",
  "2800":"Smell - Forest",     "2900":"Smell - Bread",        "3000":"Taste - Spaghetti",
  "3100":"Taste - Tomato",     "3200":"Taste - Nuts",         "3300":"Taste - Mango",
  "3400":"Taste - Rhubarb",    "3500":"Taste - Lemon",        "3600":"Taste - Cherry",
  "3700":"Taste - Custard",    "3800":"Taste - Fudge",        "3900":"Taste - Banana",
  "4000":"Touch - Sand",       "4100":"Touch - Dump",         "4200":"Touch - Newspaper",
  "4300":"Touch - Mud",        "4400":"Touch - Rock",         "4500":"Touch - Lather",
  "4600":"Touch - Jelly",      "4700":"Touch - Grass",        "4800":"Touch - Velvet",
  "4900":"Touch - Bark",       "5000":"Sensation - Swim",     "5100":"Sensation - Dancing",
  "5200":"Sensation - Nuzzling","5300":"Sensation - Mingling","5400":"Sensation - Rubbing",
  "5500":"Sensation - Loving", "5600":"Sensation - Shaking",  "5700":"Sensation - Climbing",
  "5800":"Sensation - Flying", "5900":"Sensation - Peace",    "6000":"Animals - Zebra",
  "6100":"Animals - Deer",     "6200":"Animals - Newt",       "6300":"Animals - Monkey",
  "6400":"Animals - Rhino",    "6500":"Animals - Elephant",   "6600":"Animals - Giraffe",
  "6700":"Animals - Kangaroo", "6800":"Animals - Fox",        "6900":"Animals - Bear",
  "7000":"Birds - Seagull",    "7100":"Birds - Duck",         "7200":"Birds - Nighteagle",
  "7300":"Birds - Magpie",     "7400":"Birds - Robin",        "7500":"Birds - Lark",
  "7600":"Birds - Chicken",    "7700":"Birds - Kingfisher",   "7800":"Birds - Flamingo",
  "7900":"Birds - Peacock",    "8000":"Rainbow - Red",        "8100":"Rainbow - Orange",
  "8200":"Rainbow - Yellow",   "8300":"Rainbow - Green",      "8400":"Rainbow - Blue",
  "8500":"Rainbow - Indigo",   "8600":"Rainbow - Violet",     "8700":"Rainbow - Black",
  "8800":"Rainbow - Gray",     "8900":"Rainbow - White",      "9000":"Solar-System - Sun",
  "9100":"Solar-System - Mercury","9200":"Solar-System - Venus","9300":"Solar-System - Earth",
  "9400":"Solar-System - Mars","9500":"Solar-System - Jupiter","9600":"Solar-System - Saturn",
  "9700":"Solar-System - Uranus","9800":"Solar-System - Neptune","9900":"Solar-System - Pluto"
};

// ── Month Days (Georgian ABC) ─────────────────────────────────────────────
// Quiz answer = first word of each mnemonic sentence
const MONTHS_DATA = {
   "1":"არწივი",   "2":"ბუ",         "3":"გოჭი",       "4":"დინოზავრი",
   "5":"ენოტი",    "6":"ვეშაპი",     "7":"ზებრა",      "8":"თხუნელა",
   "9":"ირემი",   "10":"კატა",      "11":"ლოკოკინა",  "12":"მგელი",
  "13":"ნიანგი",    "14":"ოფოფი",     "15":"პეპელა",    "16":"ჟირაფი",
  "17":"რჩეული", "18":"სპილო",     "19":"ტორნადო",   "20":"ულაყი",
  "21":"ფლამინგო","22":"ქამელეონი", "23":"ღამურა",    "24":"ყვავი",
  "25":"შველი",  "26":"ჩიტი",      "27":"ცხვარი",    "28":"ძროხა",
  "29":"წიწილა", "30":"ჭიამაია",   "31":"ხარი",      "32":"ჯიხვი",
  "33":"ჰიპოპოტამი"
};

// Full mnemonic sentences for the preview table
const MONTHS_FULL = {
   "1":"არწივი ანანო ამაღლებულ აივანზე",
   "2":"ბუ ბექა ბებერ ბუდეში",
   "3":"გოჭი გრიგოლი გალუმპული გემზე",
   "4":"დინოზავრი დიანა დახრილ დერეფანში",
   "5":"ენოტი ელენე ეკოლოგიურ ეზოში",
   "6":"ვეშაპი ვეფხვი ვიკა ვრცელი ვენტილატორთან",
   "7":"ზებრა ზვიადი ზუსტი ზონა",
   "8":"თხუნელა თხა თეკლა თბილი თარო",
   "9":"ირემი ირმა იშვიათი იატაკი",
  "10":"კატა კნუტი კურდღელი კესო კეთილი კარადა",
  "11":"ლოკოკინა ლიკა ლამაზი ლოგინი",
  "12":"მგელი მარიამი მგრძნობიარე მინდორი",
  "13":"ნიანგი ნინი ნაზი ნაძვნარი",
  "14":"ოფოფი ობობა ოთარი ოსტატური ოთახი",
  "15":"პეპელა პაპუნა პატიოსანი პურის ქარხანა",
  "16":"ჟირაფი ჟოზე ჟანგიან ჟალუზებთან",
  "17":"რჩეული რეზო რბილი რაფა",
  "18":"სპილო სოფო სასიამოვნო სკამი",
  "19":"ტურა ტერენტი ტკბილი ტუალეტი",
  "20":"ულაყი ულისე უდარდელი უჯრაში",
  "21":"ფლამინგო ფატი ფრთხილი ფანჯარასთან",
  "22":"ქამელეონი ქეთი ქარიანი ქოლგის ქვეშ",
  "23":"ღამურა ღვთისო ღრმა ღობე",
  "24":"ყვავი ყარამან ყვავილოვანი ყუთი",
  "25":"შველი შორენა შუშხუნა შუქნიშანთან",
  "26":"ჩიტი ჩიორა ჩუმი ჩანთაში",
  "27":"ცხვარი ციცინო ცნობისმოყვარე ცარიელ კუთხეში",
  "28":"ძროხა ძიძია ძველი ძეგლთან",
  "29":"წიწილა წიკო წითელი წინა ოთახში",
  "30":"ჭიამაია ჭრელა ჭრელ ჭიშკართან",
  "31":"ხარი ხატია ხუთვარსკვლავიან ხეზე",
  "32":"ჯიხვი ჯეინი ჯანსაღ ჯემში",
  "33":"ჰიპოპოტამი ჰექტორი ჰარმონიულ ჰოლში"
};

// ── Clocks ────────────────────────────────────────────────────────────────
// Quiz answer = clock name
const CLOCKS_DATA = {
  "12:00":"Wells Cathedral clock",
  "13:00":"Zytglogge",
  "14:00":"Prague Astronomical Clock",
  "15:00":"St Mark's Clock",
  "16:00":"Ulm Town Hall Astronomical Clock",
  "17:00":"Sighișoara Clock Tower",
  "18:00":"Astronomical Clock of Lyon",
  "19:00":"Spasskaya Tower Clock",
  "20:00":"Atlas Clock",
  "21:00":"Big Ben",
  "22:00":"Église Sainte-Croix Clock",
  "23:00":"Dolmabahçe Clock Tower",
  "00:00":"City Hall Clock",
  "01:00":"Orsay Station Clock",
  "02:00":"Edwardian Clock & Tower",
  "03:00":"Grand Central Terminal Clock",
  "04:00":"Anker Clock",
  "05:00":"Peace Tower",
  "06:00":"Selfridges Clock",
  "07:00":"Binns Clock",
  "08:00":"Allen-Bradley Clock Tower",
  "09:00":"World Clock",
  "10:00":"Leaning Clock Tower",
  "11:00":"Makkah Royal Clock Tower"
};

// Extra info shown in the preview table only
const CLOCKS_META = [
  { time:"12:00", name:"Wells Cathedral clock",          location:"England",               year:"1392", mnemonic:"DuMB Nun"      },
  { time:"13:00", name:"Zytglogge",                      location:"Bern, Switzerland",     year:"1405", mnemonic:"Tears Lollipop"},
  { time:"14:00", name:"Prague Astronomical Clock",      location:"Czech, Prague",         year:"1410", mnemonic:"Tart sauce"    },
  { time:"15:00", name:"St Mark's Clock",                location:"Venice, Italy",         year:"1499", mnemonic:"Drop Baby"     },
  { time:"16:00", name:"Ulm Town Hall Astronomical Clock",location:"Germany",              year:"1520", mnemonic:"TeLeNewS"      },
  { time:"17:00", name:"Sighișoara Clock Tower",         location:"Romania",               year:"1648", mnemonic:"DJ roof"       },
  { time:"18:00", name:"Astronomical Clock of Lyon",     location:"France, Lyon",          year:"1661", mnemonic:"Attach Judah"  },
  { time:"19:00", name:"Spasskaya Tower Clock",          location:"Russia",                year:"1852", mnemonic:"Devil Nail"    },
  { time:"20:00", name:"Atlas Clock",                    location:"Tiffany, NYC",          year:"1853", mnemonic:"Diva Lamb"     },
  { time:"21:00", name:"Big Ben",                        location:"London",                year:"1859", mnemonic:"Tough Lip"     },
  { time:"22:00", name:"Église Sainte-Croix Clock",      location:"Nantes, France",        year:"1860", mnemonic:"TV jazz"       },
  { time:"23:00", name:"Dolmabahçe Clock Tower",         location:"Istanbul, Türkiye",     year:"1895", mnemonic:"Diva Pail"     },
  { time:"00:00", name:"City Hall Clock",                location:"Philadelphia",           year:"1898", mnemonic:"Dive Buffet"   },
  { time:"01:00", name:"Orsay Station Clock",            location:"Paris",                 year:"1900", mnemonic:"Top Sauce"     },
  { time:"02:00", name:"Edwardian Clock & Tower",        location:"US, Dorchester",        year:"1905", mnemonic:"shTePSeLi"     },
  { time:"03:00", name:"Grand Central Terminal Clock",   location:"New York City",         year:"1913", mnemonic:"Top Dome"      },
  { time:"04:00", name:"Anker Clock",                    location:"Vienna, Austria",       year:"1914", mnemonic:"Debater"       },
  { time:"05:00", name:"Peace Tower",                    location:"Ottawa, Canada",        year:"1920", mnemonic:"Top news"      },
  { time:"06:00", name:"Selfridges Clock",               location:"London, Oxford St",     year:"1931", mnemonic:"Dope mad"      },
  { time:"07:00", name:"Binns Clock",                    location:"Edinburgh, Scotland",   year:"1960", mnemonic:"Top Jazz"      },
  { time:"08:00", name:"Allen-Bradley Clock Tower",      location:"Milwaukee, Wisconsin",  year:"1962", mnemonic:"BaBaJaN"       },
  { time:"09:00", name:"World Clock",                    location:"Urania, Berlin",        year:"1969", mnemonic:"Top Shop"      },
  { time:"10:00", name:"Leaning Clock Tower",            location:"Tbilisi",               year:"2011", mnemonic:"Nasty Date"    },
  { time:"11:00", name:"Makkah Royal Clock Tower",       location:"Mecca, Saudi Arabia",   year:"2011", mnemonic:"Nasty Date"    },
];
